# Generated by Django 4.2.1 on 2023-05-24 06:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0003_homework1_delete_homework'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homework1',
            new_name='Homework',
        ),
    ]
