# Generated by Django 4.2.2 on 2024-02-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
